### ISSUE TITLE
BUG: I shouldn't see the blog functionality in / NEWS

### ISSUE THREAD

**Issue by carolinewoolard** [dissentertainer/nycreic-wp#2]
@dissentertainer and @blerchin 
I don't want to see the author, date, or ability to comment anywhere on the site. Also, this page should have NEWS / PRESS, not ways to get involved. Links to things like this: http://www.upworthy.com/for-just-10-each-new-yorkers-are-taking-back-their-city-because-rent-is-too-damn-high and http://www.crainsnewyork.com/article/20150524/REAL_ESTATE/150529932

![screen shot 2015-08-22 at 2 46 02 pm](https://cloud.githubusercontent.com/assets/925548/9425390/c418c3d0-48dc-11e5-99dc-5368217fb019.png)

**Comment by dissentertainer** [comment]
Why not? The news section is just a list of news posts. That's what a blog is essentially. I can make this a static page but that's a lot more work for you on the content management side. Don't you want anyone on your team to be able to post news items?

**Comment by dissentertainer** [comment]
OK, I'm sorry. I didn't see your note above the screen shot. So get rid of all of the metadata? Even the date and category?

**Comment by carolinewoolard** [comment]
Yes please! I don't want people to know how active / inactive we are.

**Comment by dissentertainer** [comment]
I'll change it, but IMHO, it's weird to have a news item without a date.
